In [12]:
import torch

# Forward Pass with manual way 

In [13]:
x = torch.tensor([[1, 3, 6, 8]], dtype=torch.float32)
x.shape

torch.Size([1, 4])

In [14]:
w = torch.tensor([[1, 0.5, 0.7, 0.3], [1, 5, 9, 3]], dtype=torch.float32)
w.shape

torch.Size([2, 4])

In [15]:
bias=torch.tensor([0.5,1],dtype=torch.float32)
bias.shape

torch.Size([2])

In [21]:
def forward(x,w,bias):
    forward_pass= torch.matmul(x,w.T)+bias
    return forward_pass

output=forward(x,w,bias)
print(output)
print(output.shape)

tensor([[ 9.6000, 95.0000]])
torch.Size([1, 2])


# Foward Pass with Built-in functions 

In [ ]:
x=torch.tensor([[1,2,8,9]],dtype=torch.float32)

w=torch.tensor([[1,0.5,0.7,0.3],[1,5,9,3]],dtype=torch.float32)

bias=torch.tensor([0.5,1],dtype=torch.float32)

In [18]:
import torch 
import torch.nn as nn

layer= nn.Linear(in_features=4,out_features=2)

print("pytorch weights:\n", layer.weight)
print("pytorch bias:\n", layer.bias)


pytorch weights:
 Parameter containing:
tensor([[-0.2139,  0.3494,  0.3461,  0.0652],
        [-0.2394, -0.1024,  0.3484, -0.1482]], requires_grad=True)
pytorch bias:
 Parameter containing:
tensor([0.3012, 0.4310], requires_grad=True)


In [20]:
output=layer(x)
print(output)
print(output.shape)

tensor([[3.7338, 0.7889]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])
